language: erlang
sudo: false

otp_release:
- 18.2

before_install:
- wget http://s3.hex.pm/builds/elixir/v1.3.1.zip
- unzip -d elixir v1.3.1.zip

before_script:
- export PATH=`pwd`/elixir/bin:$PATH
- mix local.hex --force
- mix deps.get

script:
- MIX_ENV=test mix test
